---
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String

  ClientIP:
    Description: ClientIP 
    Type: String

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      UserData:
          Fn::Base64: !Sub |

             #!/bin/bash
             sudo yum update -y
             sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
             sudo yum install -y httpd mariadb-server 
             sudo systemctl start httpd 
             sudo systemctl enable httpd
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
      KeyName: "EC2"
  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: !Sub '${ClientIP}/32'
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
